<a href="https://colab.research.google.com/github/angel-myr/prep-python/blob/main/pandas_two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Pandas II para Data Science
---

In [2]:
import pandas as pd
import numpy as np
import random
import string

df_ventas = pd.read_csv('sales.csv')
df_ventas.head(3)

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,0,2023-08-04,293375605257,1.000,47.86,47.86,1
1,1,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,2,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1

In [3]:
def generar_codigos(cantidad):
  codigos = set()
  while len(codigos) < cantidad:
    letras = ''.join(random.choices(string.ascii_uppercase, k=4))
    numeros = ''.join(random.choices(string.digits, k=4))
    codigos.add(letras + '-' + numeros)
  return list(codigos)

In [4]:
# Asignación de Códigos únicos
codigos_ventas = generar_codigos(len(df_ventas))
df_ventas['Unnamed: 0'] = codigos_ventas
df_ventas.head(3)

,Unnamed: 0,date,item_id,quantity,price_base,sum_total,store_id
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1

In [5]:
# Cambio de nombre
df_ventas.rename(columns={'Unnamed: 0': 'code_sales'}, inplace=True)
df_ventas.head(3)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1

In [6]:
df_ventas_importantes = df_ventas[
    (df_ventas['sum_total'] > 500000.00) &
     (df_ventas['store_id'] == 4)
]
df_ventas_importantes.head(3)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
5853926,JGUJ-9229,2023-12-14,9a7e315f3f42,1056.298,591.38,624675.95,4
5866233,CBNF-3583,2023-12-16,9a7e315f3f42,921.008,589.13,542590.96,4
5935970,ZRPD-0569,2023-12-29,9a7e315f3f42,860.550,593.73,510935.61,4

## Ordenar y Agrupar Dataframes

In [7]:
df_ventas.head(5)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1
3,LOIW-2378,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1
4,UPCT-9182,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1

In [8]:
# Ordenar dataframes
df_ventas_ordenado = df_ventas.sort_values(
    by=['date', 'quantity'],
    ascending=False
)
df_ventas_ordenado.head(5)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
7431611,NEPC-5786,2024-09-26,327c5bc1e583,2797.0,0.01,24.44,4
2048054,VAJH-3032,2024-09-26,327c5bc1e583,2404.0,0.01,19.24,1
7429113,INFR-8061,2024-09-26,b0d24502fb66,1592.0,7.90,12581.03,4
2045714,TACR-1831,2024-09-26,b0d24502fb66,1495.0,7.90,11803.34,1
2046070,VBVT-0680,2024-09-26,63161948a95a,896.0,450.00,403200.00,1

In [9]:
# Agrupar por columnas
df_ventas_agrupado = df_ventas.groupby(
    by=['date', 'store_id']
)[
    ['sum_total', 'quantity']
].sum()
df_ventas_agrupado

                      sum_total   quantity
date       store_id
2022-08-28 1         2922936.17  26137.958
           2          436188.91   4887.237
           3          541857.21   4591.384
2022-08-29 1         3004918.15  26978.320
           2          568157.75   6592.772
...                         ...        ...
2024-09-25 4         4107419.80  31687.304
2024-09-26 1         4412393.49  33402.919
           2          772372.38   7899.681
           3         1126700.23   9230.439
           4         4613319.47  31355.592

[2571 rows x 2 columns]

## Fusionar Dataframes

In [10]:
df_productos = pd.read_csv('catalog.csv')

# Tabla de productos
df_productos.drop(columns=['Unnamed: 0'], inplace=True)
df_productos.head(5)

,item_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,da17e2d5feda,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,БУМАЖНАЯ ПРОДУКЦИЯ,ВЛАЖНЫЕ САЛФЕТКИ,NaN,150.0,NaN,NaN
1,614de2b96018,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN
2,0c1f1f3e3e11,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,NaN,NaN,NaN
3,71a7fa99f005,ТОВАРЫ ДЛЯ ДОМА,ПОСУДА,КУХОННАЯ ПОСУДА,NaN,NaN,NaN,NaN
4,ec1bd4d59fe9,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN

In [11]:
# Tabla de Ventas
df_ventas.head(5)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1
3,LOIW-2378,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1
4,UPCT-9182,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1

In [12]:
# Reconocer llaves foráneas
df_productos['item_id'].duplicated().sum(), df_ventas['item_id'].duplicated().sum()

(np.int64(0), np.int64(7404503))

In [13]:
# Tablas unidas
df_ventas_descriptiva = df_ventas.merge(
    df_productos,
    on='item_id',
    how='left'
)
df_ventas_descriptiva.head(5)

,code_sales,date,item_id,quantity,price_base,sum_total,store_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1,ПРИКАССА,ЖЕВАТЕЛЬНАЯ РЕЗИНКА,ПОДУШЕЧКИ,Подушечки,0.0155,0.015,NaN
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1,ЛИМОНАДЫ,НЕКОЛОСОДЕРЖАЩИЕ,"ДО 0,6Л.",Лимонады,0.5000,0.500,NaN
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1,СЛОЙКА,СЛОЙКА,СОБСТВЕННОЕ ПРОИЗВОДСТВО,Слойки,NaN,NaN,NaN
3,LOIW-2378,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1,ПЕРСОНАЛЬНЫЙ УХОД,ДЛЯ ВАННЫ И ДУША,ЖИДКОЕ МЫЛО,Жидкое Мыло,0.2000,0.200,NaN
4,UPCT-9182,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1,СОВРЕМЕННАЯ МОЛОЧНАЯ КАТЕГОРИЯ,ЙОГУРТЫ,ЙОГУРТЫ ЛОЖКОВЫЕ,Йогурты Ложковые,0.3500,0.350,1.5

In [14]:
# Tabla unida y agrupada
df_ventas_agrupado = df_ventas_descriptiva.groupby(
    by=['item_type', 'store_id']
)[[
    'sum_total', 'quantity'
]].sum()

df_ventas_agrupado

                     sum_total   quantity
item_type store_id
Абрикосы  1         2814232.81  15376.157
          2          436509.73   2286.660
          3          305720.09   1456.407
          4         1876053.91   8591.151
Авокадо   1         5800229.58  13195.515
...                        ...        ...
Яичные    1           60495.07    559.000
          2            6141.25     69.000
          4          208032.00   4409.000
Ячневая   1            8923.93    168.000
          4            8613.44    161.000

[2040 rows x 2 columns]

## Combinar Dataframes

In [15]:
# Combinación basado en índices, con prefijos en columnas de nombre repetido
df_ventas_combinado = df_ventas.join(df_productos, lsuffix='_left', rsuffix='_right')
df_ventas_combinado.head(5)

,code_sales,date,item_id_left,quantity,price_base,sum_total,store_id,item_id_right,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1,da17e2d5feda,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,БУМАЖНАЯ ПРОДУКЦИЯ,ВЛАЖНЫЕ САЛФЕТКИ,NaN,150.0,NaN,NaN
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1,614de2b96018,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1,0c1f1f3e3e11,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,NaN,NaN,NaN
3,LOIW-2378,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1,71a7fa99f005,ТОВАРЫ ДЛЯ ДОМА,ПОСУДА,КУХОННАЯ ПОСУДА,NaN,NaN,NaN,NaN
4,UPCT-9182,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1,ec1bd4d59fe9,БУМАЖНО-ВАТНАЯ ПРОДУКЦИЯ,ВАТНАЯ ПРОДУКЦИЯ,ВАТНЫЕ ДИСКИ,NaN,30.0,NaN,NaN

## Concatenar Dataframes

In [16]:
df_ventas_online = pd.read_csv('online.csv')

df_ventas_online.drop(columns=['Unnamed: 0'], inplace=True)
df_ventas_online.head(5)

         date       item_id  quantity  price_base  sum_total  store_id
0  2023-08-04  4aa8dbe05246       3.0       12.40      37.21         1
1  2023-08-04  4e0fbcf99cf9       2.0       56.27     112.54         1
2  2023-08-04  2e008b673129       2.0       56.27     112.54         1
3  2023-08-04  49db9c973903       1.0       29.94      29.94         1
4  2023-08-04  9d6072422e8e       1.0       80.10      80.10         1

In [17]:
df_ventas_offline = pd.read_csv('sales.csv')

df_ventas_offline.drop(columns=['Unnamed: 0'], inplace=True)
df_ventas_offline.head(5)

         date       item_id  quantity  price_base  sum_total  store_id
0  2023-08-04  293375605257     1.000       47.86      47.86         1
1  2023-08-04  a66fdf2c0ae7     3.000       49.60     148.80         1
2  2023-08-04  daa46ef49b7a     0.822      379.00     311.54         1
3  2023-08-04  a3b49c1bf758     1.000      129.00     129.00         1
4  2023-08-04  ab611c5cef62     7.000       79.90     559.30         1

In [18]:
# Consolidar ventas
df_ventas_consolidado = pd.concat(
    [df_ventas_offline, df_ventas_online],
    keys=['offline', 'online']
)
df_ventas_consolidado.head(5)

                 date       item_id  quantity  price_base  sum_total  store_id
offline 0  2023-08-04  293375605257     1.000       47.86      47.86         1
        1  2023-08-04  a66fdf2c0ae7     3.000       49.60     148.80         1
        2  2023-08-04  daa46ef49b7a     0.822      379.00     311.54         1
        3  2023-08-04  a3b49c1bf758     1.000      129.00     129.00         1
        4  2023-08-04  ab611c5cef62     7.000       79.90     559.30         1

In [19]:
df_ventas_offline.shape, df_ventas_online.shape, df_ventas_consolidado.shape

((7432685, 6), (1123412, 6), (8556097, 6))

In [20]:
# Consolidad opuesto (para este caso, no sirve)
df_ventas_consolidado_opuesto = pd.concat([df_ventas_offline, df_ventas_online], axis=1)
df_ventas_consolidado_opuesto.head(5)

,date,item_id,quantity,price_base,sum_total,store_id,date,item_id,quantity,price_base,sum_total,store_id
0,2023-08-04,293375605257,1.000,47.86,47.86,1,2023-08-04,4aa8dbe05246,3.0,12.40,37.21,1.0
1,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1,2023-08-04,4e0fbcf99cf9,2.0,56.27,112.54,1.0
2,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1,2023-08-04,2e008b673129,2.0,56.27,112.54,1.0
3,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1,2023-08-04,49db9c973903,1.0,29.94,29.94,1.0
4,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1,2023-08-04,9d6072422e8e,1.0,80.10,80.10,1.0

## Datos de Tiempo

In [21]:
# Generación de periodos de tiempo
df_ventas_consolidado['consolidation_time'] = pd.date_range(
    start='2026-01-01 00:00:00',
    periods=len(df_ventas_consolidado),
    freq='7s',
)
df_ventas_consolidado

                       date       item_id  quantity  price_base  sum_total  \
offline 0        2023-08-04  293375605257     1.000       47.86      47.86
        1        2023-08-04  a66fdf2c0ae7     3.000       49.60     148.80
        2        2023-08-04  daa46ef49b7a     0.822      379.00     311.54
        3        2023-08-04  a3b49c1bf758     1.000      129.00     129.00
        4        2023-08-04  ab611c5cef62     7.000       79.90     559.30
...                     ...           ...       ...         ...        ...
online  1123407  2024-09-26  039823e72e87     1.000      121.65     121.65
        1123408  2024-09-26  5879ed009378     1.330      127.83     170.01
        1123409  2024-09-26  1b7358178593     4.018       41.36     166.19
        1123410  2024-09-26  1218d0240db0     2.000       14.63      29.26
        1123411  2024-09-26  218543e3c41c     3.000      165.21     495.64

                 store_id  consolidation_time
offline 0               1 2026-01-01 00:00:00
        1               1 2026-01-01 00:00:07
        2               1 2026-01-01 00:00:14
        3               1 2026-01-01 00:00:21
        4               1 2026-01-01 00:00:28
...                   ...                 ...
online  1123407         4 2027-11-25 04:50:44
        1123408         4 2027-11-25 04:50:51
        1123409         4 2027-11-25 04:50:58
        1123410         4 2027-11-25 04:51:05
        1123411         4 2027-11-25 04:51:12

[8556097 rows x 7 columns]

In [22]:
# Cambio de tipo de dato
df_ventas_consolidado['date'] = pd.to_datetime(
    df_ventas_consolidado['date'],
    format='%Y-%m-%d'
)
df_ventas_consolidado.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8556097 entries, ('offline', np.int64(0)) to ('online', np.int64(1123411))
Data columns (total 7 columns):
 #   Column              Dtype
---  ------              -----
 0   date                datetime64[ns]
 1   item_id             object
 2   quantity            float64
 3   price_base          float64
 4   sum_total           float64
 5   store_id            int64
 6   consolidation_time  datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(1)
memory usage: 812.5+ MB

In [23]:
quantity_enteros = (df_ventas_consolidado['quantity'] % 1 == 0).sum()
quantity_flotantes = (df_ventas_consolidado['quantity'] % 1 != 0).sum()

quantity_enteros, quantity_flotantes

(np.int64(7482029), np.int64(1074068))

In [24]:
# Cálculos con series de tiempo
df_ventas_consolidado['consolidation_time'] = df_ventas_consolidado[
    'consolidation_time'
] + pd.Timedelta(seconds=1)
df_ventas_consolidado.head(5)

                date       item_id  quantity  price_base  sum_total  store_id  \
offline 0 2023-08-04  293375605257     1.000       47.86      47.86         1
        1 2023-08-04  a66fdf2c0ae7     3.000       49.60     148.80         1
        2 2023-08-04  daa46ef49b7a     0.822      379.00     311.54         1
        3 2023-08-04  a3b49c1bf758     1.000      129.00     129.00         1
        4 2023-08-04  ab611c5cef62     7.000       79.90     559.30         1

           consolidation_time
offline 0 2026-01-01 00:00:01
        1 2026-01-01 00:00:08
        2 2026-01-01 00:00:15
        3 2026-01-01 00:00:22
        4 2026-01-01 00:00:29

## Escritura de archivos

In [25]:
# Ventas del supermarket
df_supermarket = pd.read_excel('supermarket_sales.xlsx')
df_supermarket.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3

In [26]:
# Ventas Consolidadas
df_ventas_consolidado.head()

                date       item_id  quantity  price_base  sum_total  store_id  \
offline 0 2023-08-04  293375605257     1.000       47.86      47.86         1
        1 2023-08-04  a66fdf2c0ae7     3.000       49.60     148.80         1
        2 2023-08-04  daa46ef49b7a     0.822      379.00     311.54         1
        3 2023-08-04  a3b49c1bf758     1.000      129.00     129.00         1
        4 2023-08-04  ab611c5cef62     7.000       79.90     559.30         1

           consolidation_time
offline 0 2026-01-01 00:00:01
        1 2026-01-01 00:00:08
        2 2026-01-01 00:00:15
        3 2026-01-01 00:00:22
        4 2026-01-01 00:00:29

In [27]:
# Ventas resumen
df_ventas_agrupado.head()

                     sum_total   quantity
item_type store_id
Абрикосы  1         2814232.81  15376.157
          2          436509.73   2286.660
          3          305720.09   1456.407
          4         1876053.91   8591.151
Авокадо   1         5800229.58  13195.515

In [28]:
# Ventas ordenadas
df_ventas_ordenado.head()

,code_sales,date,item_id,quantity,price_base,sum_total,store_id
7431611,NEPC-5786,2024-09-26,327c5bc1e583,2797.0,0.01,24.44,4
2048054,VAJH-3032,2024-09-26,327c5bc1e583,2404.0,0.01,19.24,1
7429113,INFR-8061,2024-09-26,b0d24502fb66,1592.0,7.90,12581.03,4
2045714,TACR-1831,2024-09-26,b0d24502fb66,1495.0,7.90,11803.34,1
2046070,VBVT-0680,2024-09-26,63161948a95a,896.0,450.00,403200.00,1

In [29]:
# Ventas descriptivas (solo offline)
df_ventas_descriptiva.head()

,code_sales,date,item_id,quantity,price_base,sum_total,store_id,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,ZWFG-2001,2023-08-04,293375605257,1.000,47.86,47.86,1,ПРИКАССА,ЖЕВАТЕЛЬНАЯ РЕЗИНКА,ПОДУШЕЧКИ,Подушечки,0.0155,0.015,NaN
1,PCSZ-3308,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1,ЛИМОНАДЫ,НЕКОЛОСОДЕРЖАЩИЕ,"ДО 0,6Л.",Лимонады,0.5000,0.500,NaN
2,XBOP-6100,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1,СЛОЙКА,СЛОЙКА,СОБСТВЕННОЕ ПРОИЗВОДСТВО,Слойки,NaN,NaN,NaN
3,LOIW-2378,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1,ПЕРСОНАЛЬНЫЙ УХОД,ДЛЯ ВАННЫ И ДУША,ЖИДКОЕ МЫЛО,Жидкое Мыло,0.2000,0.200,NaN
4,UPCT-9182,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1,СОВРЕМЕННАЯ МОЛОЧНАЯ КАТЕГОРИЯ,ЙОГУРТЫ,ЙОГУРТЫ ЛОЖКОВЫЕ,Йогурты Ложковые,0.3500,0.350,1.5

In [30]:
# Ventas consolidadas y descriptivas
df_ventas_consolidado_descriptiva = df_ventas_consolidado.merge(
    df_productos,
    on='item_id',
    how='left'
)
df_ventas_consolidado_descriptiva.head()

,date,item_id,quantity,price_base,sum_total,store_id,consolidation_time,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
0,2023-08-04,293375605257,1.000,47.86,47.86,1,2026-01-01 00:00:01,ПРИКАССА,ЖЕВАТЕЛЬНАЯ РЕЗИНКА,ПОДУШЕЧКИ,Подушечки,0.0155,0.015,NaN
1,2023-08-04,a66fdf2c0ae7,3.000,49.60,148.80,1,2026-01-01 00:00:08,ЛИМОНАДЫ,НЕКОЛОСОДЕРЖАЩИЕ,"ДО 0,6Л.",Лимонады,0.5000,0.500,NaN
2,2023-08-04,daa46ef49b7a,0.822,379.00,311.54,1,2026-01-01 00:00:15,СЛОЙКА,СЛОЙКА,СОБСТВЕННОЕ ПРОИЗВОДСТВО,Слойки,NaN,NaN,NaN
3,2023-08-04,a3b49c1bf758,1.000,129.00,129.00,1,2026-01-01 00:00:22,ПЕРСОНАЛЬНЫЙ УХОД,ДЛЯ ВАННЫ И ДУША,ЖИДКОЕ МЫЛО,Жидкое Мыло,0.2000,0.200,NaN
4,2023-08-04,ab611c5cef62,7.000,79.90,559.30,1,2026-01-01 00:00:29,СОВРЕМЕННАЯ МОЛОЧНАЯ КАТЕГОРИЯ,ЙОГУРТЫ,ЙОГУРТЫ ЛОЖКОВЫЕ,Йогурты Ложковые,0.3500,0.350,1.5

In [31]:
# Exportación de tablas (Supermarket)
df_supermarket.to_csv('supermarket_sales.csv', index=False)

In [32]:
# Exportación de tablas consolidadas (Retail)
#   Por su tamaño al exportar, hago las restricciones: cantidades solo enteras (1M de registros menos)
#   y otra: solo ventas totales mayores a 1000 dólares (+6M de registros menos)

df_ventas_consolidado = df_ventas_consolidado[df_ventas_consolidado['quantity'] % 1 == 0]
df_ventas_consolidado['quantity'] = df_ventas_consolidado['quantity'].astype(int)

df_ventas_consolidado = df_ventas_consolidado[df_ventas_consolidado['sum_total'] >= 1000]
df_ventas_consolidado

/tmp/ipykernel_21682/3978868033.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ventas_consolidado['quantity'] = df_ventas_consolidado['quantity'].astype(int)

                      date       item_id  quantity  price_base  sum_total  \
offline 16      2023-08-04  68b1397119e1         2     1282.04    2564.08
        19      2023-08-04  0b211fdb94a9         5      219.90    1099.50
        25      2023-08-04  a8eedd96f742         1     1299.90    1299.90
        31      2023-08-04  5fa0bebd779f        29       42.90    1244.10
        52      2023-08-04  1e71b6b39a7e        11      209.50    2304.54
...                    ...           ...       ...         ...        ...
online  1123152 2024-09-26  f43bd6120082         1     1411.04    1411.04
        1123159 2024-09-26  e2aded14b1d3         6      286.47    1718.79
        1123305 2024-09-26  a6b6bfbc73b9         3      400.08    1200.24
        1123364 2024-09-26  98e06f94fa9f         7      338.13    2366.91
        1123374 2024-09-26  d4e6104eb37a        14      207.19    2900.60

                 store_id  consolidation_time
offline 16              1 2026-01-01 00:01:53
        19              1 2026-01-01 00:02:14
        25              1 2026-01-01 00:02:56
        31              1 2026-01-01 00:03:38
        52              1 2026-01-01 00:06:05
...                   ...                 ...
online  1123152         4 2027-11-25 04:21:00
        1123159         4 2027-11-25 04:21:49
        1123305         4 2027-11-25 04:38:51
        1123364         4 2027-11-25 04:45:44
        1123374         4 2027-11-25 04:46:54

[736727 rows x 7 columns]

In [33]:
df_ventas_consolidado_descriptiva = df_ventas_consolidado_descriptiva[
    df_ventas_consolidado_descriptiva['quantity'] % 1 == 0
]
df_ventas_consolidado_descriptiva['quantity'] = df_ventas_consolidado_descriptiva['quantity'].astype(int)

df_ventas_consolidado_descriptiva = df_ventas_consolidado_descriptiva[
    df_ventas_consolidado_descriptiva['sum_total'] >= 1000
]
df_ventas_consolidado_descriptiva

,date,item_id,quantity,price_base,sum_total,store_id,consolidation_time,dept_name,class_name,subclass_name,item_type,weight_volume,weight_netto,fatness
16,2023-08-04,68b1397119e1,2,1282.04,2564.08,1,2026-01-01 00:01:53,ТОРТЫ,КОМБИНИРОВАННЫЕ,BOCCONTO,Торты,1.100,1.100,NaN
19,2023-08-04,0b211fdb94a9,5,219.90,1099.50,1,2026-01-01 00:02:14,КОЛБАСЫ ВАРЕНЫЕ,КОЛБАСА ВАРЕНАЯ,ШТУЧНЫЕ,Вареные,0.400,0.400,NaN
25,2023-08-04,a8eedd96f742,1,1299.90,1299.90,1,2026-01-01 00:02:56,КОФЕ,КОФЕ НАТУРАЛЬНЫЙ,КОФЕ В ЗЁРНАХ ФАСОВАННЫЙ,Кофе,1.000,1.000,NaN
31,2023-08-04,5fa0bebd779f,29,42.90,1244.10,1,2026-01-01 00:03:38,ТРАДИЦИОННЫЕ МОЛОЧНЫЕ ПРОДУКТЫ,СНЕКИ,СНЕКИ,Пирожные,0.028,0.028,NaN
52,2023-08-04,1e71b6b39a7e,11,209.50,2304.54,1,2026-01-01 00:06:05,КОЛБАСЫ ВАРЕНЫЕ,КОЛБАСА ВАРЕНАЯ,ШТУЧНЫЕ,Вареные,0.500,0.500,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8555837,2024-09-26,f43bd6120082,1,1411.04,1411.04,4,2027-11-25 04:21:00,ТОРТЫ,КОМБИНИРОВАННЫЕ,BOCCONTO,Торты,1.200,1.200,NaN
8555844,2024-09-26,e2aded14b1d3,6,286.47,1718.79,4,2027-11-25 04:21:49,ПИЦЦА,ПИЦЦА,СОБСТВЕННОЕ ПРОИЗВОДСТВО,Пицца,NaN,0.800,NaN
8555990,2024-09-26,a6b6bfbc73b9,3,400.08,1200.24,4,2027-11-25 04:38:51,ТОРТЫ,БИСКВИТНЫЕ ШОКОЛАДНЫЕ,ЦЕНТРАЛИЗОВАННОЕ ПЕКАРНОЕ ПРОИЗВОДСТВО,Торты,1.000,1.000,NaN
8556049,2024-09-26,98e06f94fa9f,7,338.13,2366.91,4,2027-11-25 04:45:44,ПИЦЦА,ПИЦЦА,СОБСТВЕННОЕ ПРОИЗВОДСТВО,Пицца,NaN,0.850,NaN
8556059,2024-09-26,d4e6104eb37a,14,207.19,2900.60,4,2027-11-25 04:46:54,НАБОРЫ КОНФЕТ,НАБОРЫ КОНФЕТ НЕ ШОКОЛАДНЫЕ,НАБОРЫ КОНФЕТ НЕ ШОКОЛАДНЫЕ,Не Шоколадные,0.090,0.090,NaN

In [34]:
#df_ventas_consolidado.to_excel(
#    'retail_sales_consolidate.xlsx',
#    sheet_name='consolidate',
#    index=False
#)
#df_ventas_consolidado_descriptiva.to_excel(
#    'retail_sales_consolidate.xlsx',
#    sheet_name='consolidate_descriptive',
#    index=False
#)

In [35]:
# Exportación de tablas complementarias (Retail)
# De igual forma se hacen las restricciones, excepto a la tabla agrupada

def filtrado_ventas(df):
  df = df[df['quantity'] % 1 == 0]
  df['quantity'] = df['quantity'].astype(int)
  df = df[df['sum_total'] >= 1000]
  return df

df_ventas_offline = filtrado_ventas(df_ventas_offline)
df_ventas_online = filtrado_ventas(df_ventas_online)
df_ventas_ordenado = filtrado_ventas(df_ventas_ordenado)
df_ventas_descriptiva = filtrado_ventas(df_ventas_descriptiva)

[
    df_ventas_offline.shape,
    df_ventas_online.shape,
    df_ventas_agrupado.shape,
    df_ventas_ordenado.shape,
    df_ventas_descriptiva.shape
]

/tmp/ipykernel_21682/1548384457.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity'] = df['quantity'].astype(int)
/tmp/ipykernel_21682/1548384457.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity'] = df['quantity'].astype(int)
/tmp/ipykernel_21682/1548384457.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity'] = df['quantity'].astype(int)
/tmp/ipykernel_21682/1548384457.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quantity'] = df['quantity'].astype(int)

[(721477, 6), (15250, 6), (2040, 2), (721477, 7), (721477, 14)]

In [36]:
#with pd.ExcelWriter('retail_sales.xlsx') as writer:
#  df_ventas_offline.to_excel(writer, sheet_name='sales_off', index=False)
#  df_ventas_online.to_excel(writer, sheet_name='sales_on', index=False)
#  df_ventas_agrupado.to_excel(writer, sheet_name='sales_off_resume', index=False)
#  df_ventas_ordenado.to_excel(writer, sheet_name='sales_off_ordered', index=False)
#  df_ventas_descriptiva.to_excel(writer, sheet_name='sales_off_info', index=False)

## Acceder a segmentos del Dataframe

In [42]:
df_ventas_consolidado.head()

                 date       item_id  quantity  price_base  sum_total  \
offline 16 2023-08-04  68b1397119e1         2     1282.04    2564.08
        19 2023-08-04  0b211fdb94a9         5      219.90    1099.50
        25 2023-08-04  a8eedd96f742         1     1299.90    1299.90
        31 2023-08-04  5fa0bebd779f        29       42.90    1244.10
        52 2023-08-04  1e71b6b39a7e        11      209.50    2304.54

            store_id  consolidation_time
offline 16         1 2026-01-01 00:01:53
        19         1 2026-01-01 00:02:14
        25         1 2026-01-01 00:02:56
        31         1 2026-01-01 00:03:38
        52         1 2026-01-01 00:06:05

In [51]:
# Uso de .loc
df_ventas_consolidado.index

MultiIndex([('offline',      16),
            ('offline',      19),
            ('offline',      25),
            ('offline',      31),
            ('offline',      52),
            ('offline',      57),
            ('offline',      87),
            ('offline',      91),
            ('offline',      96),
            ('offline',      97),
            ...
            ( 'online', 1122874),
            ( 'online', 1122898),
            ( 'online', 1122904),
            ( 'online', 1122980),
            ( 'online', 1123042),
            ( 'online', 1123152),
            ( 'online', 1123159),
            ( 'online', 1123305),
            ( 'online', 1123364),
            ( 'online', 1123374)],
           length=736727)

In [57]:
df_ventas_consolidado.loc[[('offline', 16), ('online', 1123042)]]

,,date,item_id,quantity,price_base,sum_total,store_id,consolidation_time
offline,16,2023-08-04,68b1397119e1,2,1282.04,2564.08,1,2026-01-01 00:01:53
online,1123042,2024-09-26,44543436333f,22,109.27,2403.97,4,2027-11-25 04:08:10

In [59]:
df_ventas_consolidado.loc[('offline', 52): ('online', 1122874)]

                      date       item_id  quantity  price_base  sum_total  \
offline 52      2023-08-04  1e71b6b39a7e        11      209.50    2304.54
        57      2023-08-04  ea8f78452b8a         1     1150.90    1150.90
        87      2023-08-04  8ab850c0c739        24       62.86    1508.68
        91      2023-08-04  f43bd6120082         1     1350.00    1350.00
        96      2023-08-04  ff88c2914cd0        13       79.90    1038.70
...                    ...           ...       ...         ...        ...
online  1122700 2024-09-26  1f159bf8e2d1        12       91.48    1097.80
        1122775 2024-09-26  4965e554971b         2      566.80    1133.60
        1122779 2024-09-26  e2f0530d0f6e        11       97.50    1072.48
        1122816 2024-09-26  27d12fd9f94f         2      922.63    1845.26
        1122874 2024-09-26  f3c06ac8099b         5      780.10    3900.52

                 store_id  consolidation_time
offline 52              1 2026-01-01 00:06:05
        57              1 2026-01-01 00:06:40
        87              1 2026-01-01 00:10:10
        91              1 2026-01-01 00:10:38
        96              1 2026-01-01 00:11:13
...                   ...                 ...
online  1122700         4 2027-11-25 03:28:16
        1122775         4 2027-11-25 03:37:01
        1122779         4 2027-11-25 03:37:29
        1122816         4 2027-11-25 03:41:48
        1122874         4 2027-11-25 03:48:34

[736714 rows x 7 columns]

In [69]:
df_ventas_consolidado.loc[
    (df_ventas_consolidado['consolidation_time'] >= '2027-06-01') &
    (df_ventas_consolidado['consolidation_time'] <= '2027-06-30')
]

                      date       item_id  quantity  price_base  sum_total  \
offline 6368915 2024-03-21  1ba493053c46         3     1416.39    4249.16
        6368927 2024-03-21  45d19024774d         4      748.99    2995.97
        6368930 2024-03-21  2845297e0cb7         2      899.90    1799.80
        6368933 2024-03-21  21ff169bf530        15      152.75    2291.31
        6368936 2024-03-21  d901b1325fec        25       42.79    1069.70
...                    ...           ...       ...         ...        ...
        6726843 2024-05-24  4f33b8ca89bf         5      499.90    2499.50
        6726844 2024-05-24  75220cb120df         3     1790.00    5370.00
        6726853 2024-05-24  e4bb62e35936         6      198.85    1193.12
        6726855 2024-05-24  b15adc9a5013         4      691.62    2766.49
        6726857 2024-05-24  417df0603f41        60       89.19    5351.53

                 store_id  consolidation_time
offline 6368915         4 2027-06-01 00:00:06
        6368927         4 2027-06-01 00:01:30
        6368930         4 2027-06-01 00:01:51
        6368933         4 2027-06-01 00:02:12
        6368936         4 2027-06-01 00:02:33
...                   ...                 ...
        6726843         4 2027-06-29 23:58:22
        6726844         4 2027-06-29 23:58:29
        6726853         4 2027-06-29 23:59:32
        6726855         4 2027-06-29 23:59:46
        6726857         4 2027-06-30 00:00:00

[40944 rows x 7 columns]

In [75]:
# Uso de .iloc
df_ventas_consolidado.iloc[0:16]

                  date       item_id  quantity  price_base  sum_total  \
offline 16  2023-08-04  68b1397119e1         2     1282.04    2564.08
        19  2023-08-04  0b211fdb94a9         5      219.90    1099.50
        25  2023-08-04  a8eedd96f742         1     1299.90    1299.90
        31  2023-08-04  5fa0bebd779f        29       42.90    1244.10
        52  2023-08-04  1e71b6b39a7e        11      209.50    2304.54
        57  2023-08-04  ea8f78452b8a         1     1150.90    1150.90
        87  2023-08-04  8ab850c0c739        24       62.86    1508.68
        91  2023-08-04  f43bd6120082         1     1350.00    1350.00
        96  2023-08-04  ff88c2914cd0        13       79.90    1038.70
        97  2023-08-04  b22bd41ce0bb         3      791.70    2375.10
        98  2023-08-04  f1c124cf6cca        28       49.80    1394.42
        99  2023-08-04  56e8140a6950         9      236.21    2125.89
        103 2023-08-04  a1a85a5a80ac         8      177.00    1416.00
        104 2023-08-04  17004ddc7507        19       79.54    1511.21
        106 2023-08-04  79fdc441b59f        82      128.90   10569.52
        110 2023-08-04  c2149157e294        20       69.86    1397.20

             store_id  consolidation_time
offline 16          1 2026-01-01 00:01:53
        19          1 2026-01-01 00:02:14
        25          1 2026-01-01 00:02:56
        31          1 2026-01-01 00:03:38
        52          1 2026-01-01 00:06:05
        57          1 2026-01-01 00:06:40
        87          1 2026-01-01 00:10:10
        91          1 2026-01-01 00:10:38
        96          1 2026-01-01 00:11:13
        97          1 2026-01-01 00:11:20
        98          1 2026-01-01 00:11:27
        99          1 2026-01-01 00:11:34
        103         1 2026-01-01 00:12:02
        104         1 2026-01-01 00:12:09
        106         1 2026-01-01 00:12:23
        110         1 2026-01-01 00:12:51

## Aplicación 2.0

#### Producto más vendido

In [89]:
# Tabla de ventas por Producto ordenado y resumido en millones de dólares
df_ventas_consolidado.groupby(by='item_id')[
    ['quantity', 'sum_total']
].sum().assign(
    sum_total=lambda x: x['sum_total'] / 1_000_000
).round(2).sort_values(
    by='sum_total', ascending=False
).head(10)

              quantity  sum_total
item_id
63161948a95a    434289     195.43
9b4865c6faf1    178424      17.37
79fdc441b59f    138091      16.99
f1eb9c33424e    159609      15.47
e2aded14b1d3     29476      15.44
f202f07102b7      9758      15.13
b0d24502fb66   2015262      15.06
d9f5cbd8e676    144893      14.16
0bd1661c472e     44111      13.60
6d284b4e9982    223121      12.82

#### Mes con más ventas

In [94]:
# Tabla de ventas por Mes resumido en millones
df_ventas_consolidado.groupby(by=df_ventas_consolidado['date'].dt.month)[
    ['quantity', 'sum_total']
].sum().assign(
    sum_total=lambda x: x['sum_total'] / 1_000_000
).round(2)

      quantity  sum_total
date
1      1200798     151.39
2      1254384     160.36
3      1471238     194.52
4      1424315     168.34
5      1510964     185.11
6      1440621     172.25
7      1490713     176.93
8      1543613     187.67
9      1848986     217.91
10     1013479     115.40
11      953299     111.00
12     1461947     210.04