<a href="https://colab.research.google.com/github/angel-myr/prep-python/blob/main/pandas_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Pandas para Data Science
---

## Dataframe

In [29]:
import pandas as pd

df_ventas = pd.read_excel('supermarket_sales.xlsx')
df_ventas.head(3)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4

In [33]:
df_ventas.tail(3)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.592,33.432,2019-02-09,13:22:00,Cash,31.84,4.761905,1.592,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.291,69.111,2019-02-22,15:33:00,Cash,65.82,4.761905,3.291,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.919,649.299,2019-02-18,13:28:00,Cash,618.38,4.761905,30.919,6.6

In [37]:
df_ventas.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [39]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [40]:
df_ventas.describe()

,Unit price,Quantity,Tax 5%,Total,Date,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,2019-02-14 00:05:45.600000,307.58738,4.761905e+00,15.379369,6.97270
min,10.080000,1.000000,0.508500,10.678500,2019-01-01 00:00:00,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,2019-01-24 00:00:00,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,2019-02-13 00:00:00,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,2019-03-08 00:00:00,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,2019-03-30 00:00:00,993.00000,4.761905e+00,49.650000,10.00000
std,26.494628,2.923431,11.708825,245.885335,NaN,234.17651,6.131498e-14,11.708825,1.71858

## Serie

In [44]:
sr_product = df_ventas['Product line']
sr_product.head(5)

0         Health and beauty
1    Electronic accessories
2        Home and lifestyle
3         Health and beauty
4         Sports and travel
Name: Product line, dtype: object

In [51]:
datos = [10, 20, 30, 40, 50]
serie_datos = pd.Series(datos)

indices = ['a', 'b', 'c', 'd', 'e']
serie_datos_indices = pd.Series(datos, index=indices)
serie_datos, serie_datos_indices, serie_datos_indices['e']

(0    10
 1    20
 2    30
 3    40
 4    50
 dtype: int64,
 a    10
 b    20
 c    30
 d    40
 e    50
 dtype: int64,
 np.int64(50))

In [52]:
selecciones = {"Portugal": "Lisboa", "España": "Madrid", "Francia": "Paris"}
serie_selecciones = pd.Series(selecciones)
serie_selecciones

Portugal    Lisboa
España      Madrid
Francia      Paris
dtype: object

## Operaciones Básicas con Series

In [56]:
serie_1 = pd.Series([1, 2, 3, 4, 5])
serie_2 = pd.Series([10, 20, 30, 40, 50])

serie_1 = serie_1 ** 2
serie_1

0     1
1     4
2     9
3    16
4    25
dtype: int64

## Limpieza de Datos

In [60]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [62]:
# Cantidad nulos
df_ventas.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [63]:
# Eliminar nulos
df_ventas_filtro = df_ventas.dropna()
df_ventas_filtro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [65]:
# Nulos rellenados
valores_relleno = {"Time": '00:00:00', "Quantity": df_ventas['Quantity'].mean()}
df_ventas_rellenados = df_ventas.fillna(valores_relleno)
df_ventas_rellenados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [67]:
# Cambio de tipo
df_ventas_rellenados["Quantity"] = df_ventas_rellenados['Quantity'].astype(int)
df_ventas_rellenados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [68]:
# Eliminar duplicados
df_ventas_unicos = df_ventas.drop_duplicates()
df_ventas_unicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [70]:
# Eliminar duplicados parciales
df_ventas_unicos = df_ventas.drop_duplicates(subset='Invoice ID')
df_ventas_unicos.head(3)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4

## Filtrado de Series

In [79]:
serie_totales = pd.Series(df_ventas['Total'])
serie_totales.head(5)

0    548.9715
1     80.2200
2    340.5255
3    489.0480
4    634.3785
Name: Total, dtype: float64

In [88]:
# Filtrado de Series Numeral
filtro = serie_totales > serie_totales.mean()
serie_filtrada = serie_totales[filtro]
serie_filtrada, serie_filtrada.count(), serie_totales.count(), serie_totales.mean()

(0       548.9715
 2       340.5255
 3       489.0480
 4       634.3785
 5       627.6165
          ...
 988     864.5700
 989     633.1080
 991     804.3000
 996    1022.4900
 999     649.2990
 Name: Total, Length: 404, dtype: float64,
 np.int64(404),
 np.int64(1000),
 np.float64(322.966749))

In [101]:
# Filtrado de Series Cadenas
serie_ciudad = pd.Series(df_ventas['City'])
filtro = serie_ciudad.str.contains('M|m')
serie_filtrada = serie_ciudad[filtro]
serie_filtrada, serie_filtrada.count(), serie_ciudad.count()

(9      Mandalay
 10     Mandalay
 11     Mandalay
 15     Mandalay
 19     Mandalay
          ...
 987    Mandalay
 989    Mandalay
 991    Mandalay
 993    Mandalay
 996    Mandalay
 Name: City, Length: 332, dtype: object,
 np.int64(332),
 np.int64(1000))

## Agregaciones de Series

In [106]:
promedio_ventas = serie_totales.mean()
suma_ventas = serie_totales.sum()
minimo_ventas = serie_totales.min()
maximo_ventas = serie_totales.max()
varianza_ventas = serie_totales.std()

promedio_ventas, suma_ventas, minimo_ventas, maximo_ventas, varianza_ventas

(np.float64(322.966749),
 np.float64(322966.749),
 10.6785,
 1042.65,
 245.88533510097207)

## Proyecto Aplicativo

In [108]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   datetime64[ns]
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 132.9+ KB

In [112]:
df_ventas[['Invoice ID', 'Customer type', 'Total']]

      Invoice ID Customer type      Total
0    750-67-8428        Member   548.9715
1    226-31-3081        Normal    80.2200
2    631-41-3108        Normal   340.5255
3    123-19-1176        Member   489.0480
4    373-73-7910        Normal   634.3785
..           ...           ...        ...
995  233-67-5758        Normal    42.3675
996  303-96-2227        Normal  1022.4900
997  727-02-1313        Member    33.4320
998  347-56-2442        Normal    69.1110
999  849-09-3807        Member   649.2990

[1000 rows x 3 columns]

In [116]:
df_ventas_resume = df_ventas[['Invoice ID', 'Customer type', 'Total']].copy()
df_ventas_resume = df_ventas_resume.sort_values(by='Total', ascending=False)
df_ventas_resume.head(5)

      Invoice ID Customer type    Total
350  860-79-0874        Member  1042.65
167  687-47-8271        Normal  1039.29
557  283-26-5248        Member  1034.46
699  751-41-9720        Normal  1023.75
996  303-96-2227        Normal  1022.49

In [121]:
df_ventas_resume.duplicated('Invoice ID').sum()

np.int64(0)

In [142]:
filtro = df_ventas_resume['Customer type'].str.contains('Member')
df_ventas_resume_filtrado = df_ventas_resume[filtro]
df_ventas_resume_filtrado.head(5)

      Invoice ID Customer type     Total
350  860-79-0874        Member  1042.650
557  283-26-5248        Member  1034.460
422  271-88-8734        Member  1020.705
429  325-77-6186        Member   951.825
141  280-17-4359        Member   950.250

In [144]:
filtro = df_ventas_resume_filtrado['Invoice ID'].str.contains('^25')
df_ventas_resume_filtrado = df_ventas_resume_filtrado[filtro]
df_ventas_resume_filtrado

      Invoice ID Customer type    Total
265  253-12-6086        Member  723.240
436  257-73-1380        Member  348.306
369  254-31-0042        Member  203.175
758  250-17-5703        Member  197.925
960  256-58-3609        Member   96.579